<a href="https://colab.research.google.com/github/Axl11475581/TensorFlow-Certificate/blob/main/0_1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook the exercises from the **0.0 - Fundamentals** will be cover.

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# vector
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [3]:
# scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# matrix
matrix = tf.constant([[5, 7],
                     [4, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [4, 5]], dtype=int32)>

2. Find the shape, rank and size of the tensor you created in 1.

In [5]:
# Vector:

# shape:
vector.shape

# rank:
vector.ndim

# size:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
# Scalar:

# shape: 
scalar.shape

# rank:
scalar.ndim

# size:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
# Matrix:

# shape:
matrix.shape

# rank:
matrix.ndim

# size:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

3. Create two tensor containing random values between 0 and 1 with shape [5, 300]

In [9]:
tensor_1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.725834  , 0.7144027 , 0.7009554 , ..., 0.7541951 , 0.5942961 ,
        0.6161767 ],
       [0.10624433, 0.9182825 , 0.3053527 , ..., 0.83197653, 0.6211585 ,
        0.7405844 ],
       [0.87477076, 0.48703992, 0.6091914 , ..., 0.6536323 , 0.70136416,
        0.61156464],
       [0.2970872 , 0.854797  , 0.37588418, ..., 0.25407135, 0.9595425 ,
        0.9783243 ],
       [0.2558726 , 0.46905243, 0.39957023, ..., 0.9870672 , 0.8249458 ,
        0.3297552 ]], dtype=float32)>

In [11]:
tensor_2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.70492685, 0.59165525, 0.9984342 , ..., 0.82377195, 0.50674176,
        0.2056905 ],
       [0.7274715 , 0.58019364, 0.0781678 , ..., 0.8165554 , 0.81640613,
        0.7101613 ],
       [0.5995698 , 0.5434029 , 0.660071  , ..., 0.92204845, 0.63784325,
        0.30433464],
       [0.98738813, 0.32114148, 0.34647787, ..., 0.362908  , 0.11932373,
        0.1422894 ],
       [0.21746552, 0.07633471, 0.8544364 , ..., 0.42927635, 0.35266197,
        0.4993781 ]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [12]:
# change the shape of tensor_2 to match the rules of matrix multiplication
tensor_1 @ tf.reshape(tensor_2, shape=(300, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.92303 , 73.27257 , 70.05194 , 75.84441 , 72.18917 ],
       [78.17239 , 75.457596, 74.532166, 79.54445 , 78.01886 ],
       [81.70579 , 80.546555, 78.92348 , 85.536606, 83.959915],
       [73.7735  , 73.531204, 71.62265 , 76.188644, 73.38219 ],
       [76.32632 , 75.52974 , 73.93538 , 79.377396, 76.60255 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [13]:
tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.725834  , 0.7144027 , 0.7009554 , ..., 0.7541951 , 0.5942961 ,
         0.6161767 ],
        [0.10624433, 0.9182825 , 0.3053527 , ..., 0.83197653, 0.6211585 ,
         0.7405844 ],
        [0.87477076, 0.48703992, 0.6091914 , ..., 0.6536323 , 0.70136416,
         0.61156464],
        [0.2970872 , 0.854797  , 0.37588418, ..., 0.25407135, 0.9595425 ,
         0.9783243 ],
        [0.2558726 , 0.46905243, 0.39957023, ..., 0.9870672 , 0.8249458 ,
         0.3297552 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.70492685, 0.59165525, 0.9984342 , ..., 0.82377195, 0.50674176,
         0.2056905 ],
        [0.7274715 , 0.58019364, 0.0781678 , ..., 0.8165554 , 0.81640613,
         0.7101613 ],
        [0.5995698 , 0.5434029 , 0.660071  , ..., 0.92204845, 0.63784325,
         0.30433464],
        [0.98738813, 0.32114148, 0.34647787, ..., 0.362908  , 0.11932373,
         0.1422894 ],
        [0.21746

In [14]:
# performing the dot product on tensor_1 and tensor_2 (requires one of them to be transposed)
tf.tensordot(tf.transpose(tensor_2), tensor_1, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.4624195 , 2.4096594 , 1.5395467 , ..., 1.9943099 , 2.4181654 ,
        2.3774855 ],
       [1.0813777 , 1.5304364 , 1.0741371 , ..., 1.441057  , 1.4642547 ,
        1.4659249 ],
       [1.6319742 , 1.8034889 , 1.597479  , ..., 2.180908  , 2.1421943 ,
        1.6975003 ],
       ...,
       [1.7089125 , 2.2989736 , 1.6964062 , ..., 2.4192495 , 2.3458219 ,
        2.1728072 ],
       [1.1382016 , 1.6897788 , 1.178829  , ..., 1.8567456 , 1.6610559 ,
        1.5399718 ],
       [0.66102034, 1.3031607 , 0.79944855, ..., 1.4739627 , 1.3253058 ,
        1.1426741 ]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [15]:
tensor_3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.90273046, 0.17546177, 0.6244786 ],
        [0.90424705, 0.55866647, 0.9286822 ],
        [0.5152645 , 0.3546884 , 0.36974335],
        ...,
        [0.5681802 , 0.3315735 , 0.81942856],
        [0.9881035 , 0.4535743 , 0.00692081],
        [0.77889943, 0.18948257, 0.16100264]],

       [[0.192276  , 0.29310942, 0.18879044],
        [0.18848026, 0.09411788, 0.31751525],
        [0.59260106, 0.35365832, 0.21050179],
        ...,
        [0.32908022, 0.38025558, 0.33968484],
        [0.4718126 , 0.21941924, 0.5672258 ],
        [0.41869354, 0.15425968, 0.18815696]],

       [[0.48585677, 0.7939764 , 0.0577985 ],
        [0.4339912 , 0.09429932, 0.5883461 ],
        [0.8335959 , 0.10632885, 0.12551558],
        ...,
        [0.8663775 , 0.02666056, 0.9042989 ],
        [0.03039014, 0.71201134, 0.6049417 ],
        [0.9778528 , 0.93867564, 0.9619217 ]],

       ...,

       [[0.6704309 , 0.8251151 , 0.02587605],
        [0.52

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [19]:
# Find the minimum
tf.reduce_min(tensor_3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[2.14159489e-03, 3.58211994e-03, 5.68556786e-03],
       [7.33065605e-03, 2.32350826e-03, 9.67621803e-04],
       [2.24590302e-04, 7.78007507e-03, 5.21183014e-04],
       [2.00796127e-03, 1.10054016e-03, 3.36289406e-04],
       [1.94287300e-03, 6.16884232e-03, 1.23680830e-02],
       [3.94880772e-03, 5.69355488e-03, 1.91199780e-03],
       [1.28382444e-02, 9.88388062e-03, 1.23043060e-02],
       [8.69631767e-03, 1.36989355e-02, 5.12456894e-03],
       [6.38830662e-03, 8.01563263e-04, 6.96527958e-03],
       [1.57451630e-03, 9.18900967e-03, 4.77194786e-03],
       [5.74195385e-03, 2.07805634e-03, 7.03632832e-03],
       [5.47170639e-04, 6.90281391e-03, 8.46266747e-04],
       [5.30695915e-03, 4.98402119e-03, 3.36837769e-03],
       [2.92503834e-03, 2.16482878e-02, 1.30748749e-03],
       [2.29740143e-03, 2.44665146e-03, 2.87485123e-03],
       [2.29084492e-03, 1.08945370e-03, 6.23703003e-04],
       [1.61409378e-04, 7.99894333e-05

In [20]:
# Find the maximum
tf.reduce_max(tensor_3, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99873257, 0.99884665, 0.9970497 ],
       [0.9970305 , 0.99036133, 0.9954244 ],
       [0.9990246 , 0.9999976 , 0.9997897 ],
       [0.9959551 , 0.9996407 , 0.9993495 ],
       [0.99815834, 0.97867274, 0.9887738 ],
       [0.99795294, 0.9992157 , 0.9952233 ],
       [0.9966202 , 0.99421275, 0.99956286],
       [0.995589  , 0.9927561 , 0.9907737 ],
       [0.9982865 , 0.99889445, 0.99937785],
       [0.99862194, 0.99934566, 0.98654354],
       [0.9924475 , 0.9967731 , 0.9992132 ],
       [0.9890808 , 0.9994345 , 0.9901247 ],
       [0.99636865, 0.99884284, 0.9827746 ],
       [0.9873338 , 0.9846821 , 0.9940165 ],
       [0.97942436, 0.99939954, 0.9988017 ],
       [0.9974766 , 0.9880848 , 0.9982858 ],
       [0.9944283 , 0.99180317, 0.99991226],
       [0.9996309 , 0.99756896, 0.99250627],
       [0.9941455 , 0.99855566, 0.9972439 ],
       [0.9992713 , 0.99721694, 0.9988078 ],
       [0.9945307 , 0.9973134 , 0.9982313 ],
     

8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [22]:
tensor_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.5583354 , 0.31812394, 0.70282876],
         [0.91324306, 0.15856957, 0.9420465 ],
         [0.29311502, 0.40667093, 0.36895764],
         ...,
         [0.8147533 , 0.51181614, 0.5732759 ],
         [0.6159233 , 0.9794086 , 0.53063107],
         [0.23406029, 0.4755566 , 0.00598609]],

        [[0.13511944, 0.93321013, 0.07811058],
         [0.3327099 , 0.45086884, 0.23091674],
         [0.34278095, 0.8526406 , 0.66242504],
         ...,
         [0.5102602 , 0.01405263, 0.6302562 ],
         [0.7163956 , 0.28106678, 0.60189986],
         [0.02097845, 0.6932752 , 0.39188004]],

        [[0.28475118, 0.57998145, 0.14773369],
         [0.8750018 , 0.5306891 , 0.7468357 ],
         [0.7936541 , 0.62646186, 0.18829072],
         ...,
         [0.6753441 , 0.11576593, 0.97981143],
         [0.93672156, 0.01999533, 0.0404557 ],
         [0.41392732, 0.94288945, 0.98175013]],

        ...,

        [[0.17989731, 0.59782684, 

In [23]:
tensor_4.shape

TensorShape([1, 224, 224, 3])

In [24]:
tensor_4_squeezed = tf.squeeze(tensor_4)
tensor_4_squeezed, tensor_4_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.5583354 , 0.31812394, 0.70282876],
         [0.91324306, 0.15856957, 0.9420465 ],
         [0.29311502, 0.40667093, 0.36895764],
         ...,
         [0.8147533 , 0.51181614, 0.5732759 ],
         [0.6159233 , 0.9794086 , 0.53063107],
         [0.23406029, 0.4755566 , 0.00598609]],
 
        [[0.13511944, 0.93321013, 0.07811058],
         [0.3327099 , 0.45086884, 0.23091674],
         [0.34278095, 0.8526406 , 0.66242504],
         ...,
         [0.5102602 , 0.01405263, 0.6302562 ],
         [0.7163956 , 0.28106678, 0.60189986],
         [0.02097845, 0.6932752 , 0.39188004]],
 
        [[0.28475118, 0.57998145, 0.14773369],
         [0.8750018 , 0.5306891 , 0.7468357 ],
         [0.7936541 , 0.62646186, 0.18829072],
         ...,
         [0.6753441 , 0.11576593, 0.97981143],
         [0.93672156, 0.01999533, 0.0404557 ],
         [0.41392732, 0.94288945, 0.98175013]],
 
        ...,
 
        [[0.17989731, 0.59782684