<a href="https://colab.research.google.com/github/Axl11475581/TensorFlow-Certificate/blob/main/0_1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook the exercises from the **0.0 - Fundamentals** will be cover.

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# vector
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [3]:
# scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# matrix
matrix = tf.constant([[5, 7],
                     [4, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [4, 5]], dtype=int32)>

2. Find the shape, rank and size of the tensor you created in 1.

In [5]:
# Vector:

# shape:
vector.shape

# rank:
vector.ndim

# size:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
# Scalar:

# shape: 
scalar.shape

# rank:
scalar.ndim

# size:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
# Matrix:

# shape:
matrix.shape

# rank:
matrix.ndim

# size:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

3. Create two tensor containing random values between 0 and 1 with shape [5, 300]

In [9]:
tensor_1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.725834  , 0.7144027 , 0.7009554 , ..., 0.7541951 , 0.5942961 ,
        0.6161767 ],
       [0.10624433, 0.9182825 , 0.3053527 , ..., 0.83197653, 0.6211585 ,
        0.7405844 ],
       [0.87477076, 0.48703992, 0.6091914 , ..., 0.6536323 , 0.70136416,
        0.61156464],
       [0.2970872 , 0.854797  , 0.37588418, ..., 0.25407135, 0.9595425 ,
        0.9783243 ],
       [0.2558726 , 0.46905243, 0.39957023, ..., 0.9870672 , 0.8249458 ,
        0.3297552 ]], dtype=float32)>

In [11]:
tensor_2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.70492685, 0.59165525, 0.9984342 , ..., 0.82377195, 0.50674176,
        0.2056905 ],
       [0.7274715 , 0.58019364, 0.0781678 , ..., 0.8165554 , 0.81640613,
        0.7101613 ],
       [0.5995698 , 0.5434029 , 0.660071  , ..., 0.92204845, 0.63784325,
        0.30433464],
       [0.98738813, 0.32114148, 0.34647787, ..., 0.362908  , 0.11932373,
        0.1422894 ],
       [0.21746552, 0.07633471, 0.8544364 , ..., 0.42927635, 0.35266197,
        0.4993781 ]], dtype=float32)>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [12]:
# change the shape of tensor_2 to match the rules of matrix multiplication
tensor_1 @ tf.reshape(tensor_2, shape=(300, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.92303 , 73.27257 , 70.05194 , 75.84441 , 72.18917 ],
       [78.17239 , 75.457596, 74.532166, 79.54445 , 78.01886 ],
       [81.70579 , 80.546555, 78.92348 , 85.536606, 83.959915],
       [73.7735  , 73.531204, 71.62265 , 76.188644, 73.38219 ],
       [76.32632 , 75.52974 , 73.93538 , 79.377396, 76.60255 ]],
      dtype=float32)>