<a href="https://colab.research.google.com/github/Axl11475581/TensorFlow-Certificate/blob/main/0_1_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook the exercises from the **0.0 - Fundamentals** will be cover.

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# vector
vector = tf.constant([5, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

In [3]:
# scalar
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# matrix
matrix = tf.constant([[5, 7],
                     [4, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 7],
       [4, 5]], dtype=int32)>

2. Find the shape, rank and size of the tensor you created in 1.

In [5]:
# Vector:

# shape:
vector.shape

# rank:
vector.ndim

# size:

tf.size(vector)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
# Scalar:

# shape: 
scalar.shape

# rank:
scalar.ndim

# size:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
# Matrix:

# shape:
matrix.shape

# rank:
matrix.ndim

# size:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=4>